before_script:
- cd server
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- cd ..
deploy:
  provider: heroku
  api_key:
    secure: n/Pnzfj0mO/F6mSMaNGeclvRbtJe3sYAOB+uVxzUjhvZu6O8kVHXBCUtq+5pYHdOrEruUNQITJy8m8lj0opn15zU/4+4xEJVtWC4D5GvpQqK0/DapyG8KkdtWUkxuk+D2LeWyDOAV5o6uCSIWMYJIRWAaTv7DLX38llNZwF7+RmTHEmo36JCm47tZV/UDXCcg8EcT1kO571rRMBhvQptQ01LKUK+vuRrag2evqmk637clusT4W3QMckZTRDkIHFZNNVzFshRVDdnp61ssc+AtayYQFp939b7Bxns1Bi3x5GBdElqmwQrmXghg7XHIjxvlH5HHl09XCsZ6YUitVnozgUpD0YaKjkeZrGC+al42SByAH2Ler+nX8VwHxJs85NzELlvHXcZBH1qMHr8K6kEhFStlBmXjeF2Mq+HFAe5NLdZmcW6JiJVgjXF7NoquGWLXWm30aVhIonnvbqhI/ritNueT6MWJzRhN0AeZuI00OJh4iOEev8hVTb1/vhgdKmw7UQHuAdRsYUryBEtlusSRMM6GsKsbkS6lcfpqTiRW2ksnVp93NEew34wxbbO51gyjzLfxlpsIAghujrNyYYehCCdsEuxqMP4NT2rUHu85WqKgnxG956uNPGU1qxQmaD3AgdYl9o7srwIJmp7iLptz3XcjiQQTnUzdNyP9koymLw=
  app: vibhaag
notifications:
  slack: pesumca:eSl80BeI8cTUfXW5OiwBiYOX